unit userscript;

//Under "const" are settings that are safe to change
//Inside "Initialize" are a large number of booleans. These are on/off (true/false) settings
//Set them to false to not duplicate those NPCs

const
	bUseExistingFile = true; //Whether or not to use an existing .esp generated by this script
	strFileNamePrefix = 'FyTy - More Spawns'; //Used when generating a unique .esp file
	strFileName = 'FyTy - More Spawns001.esm'; //The name of an existing mod file. Only used if: bUseExistingFile = true;
	iMinMultiplier = 1; //The minimum number of times to duplicate a spawn. Must be (>= 0) and (<= iMaxMultiplier)
	iMaxMultiplier = 3; //The maimum number of times to duplicate a spawn. Must be (> 0) and (>= iMinMultiplier)
	bCopyIfESP = false; //If true, the spawn will be duplicated, even if it's from a .esp file

var
	tstrlistMasters,
	tstrlistAll,
	tstrlistAlienRobots, tstrlistAbominations, tstrlistAliens, tstrlistBandits, tstrlistFiends,
	tstrlistMarkedMen, tstrlistSlavers, tstrlistPowderGangers, tstrlistTalon, tstrlistRaiders,
	tstrlistCentaurs, tstrlistNightkin, tstrlistSuperMutants, tstrlistBoomers, tstrlistOutcasts,
	tstrlistBoS, tstrlistNCR, tstrlistLegion, tstrlistEnclave, tstrlistTribals, tstrlistChinese,
	tstrlistFeralGhouls, tstrlistLobotomites, tstrlistDeathclaws, tstrlistTunnellers, tstrlistTrogs,
	tstrlistLakelurks, tstrlistSpores, tstrlistRobots, tstrlistMirelurks, tstrlistAnimals,
	tstrlistInsects: TStringList;
	
	bAlienRobots, bAbominations, bAliens, bBandits, bFiends, bMarkedMen, bSlavers, bPowderGangers,
	bTalon, bRaiders, bCentaurs, bNightkin, bSuperMutants, bBoomers, bOutcasts, bBoS, bNCR, bLegion,
	bEnclave, bTribals, bChinese, bFeralGhouls, bLobotomites, bDeathclaws, bTrogs, bTunnellers, bLakelurks,
	bSpores, bRobots, bMirelurks, bAnimals, bInsects: boolean;
	
	fileDest: IInterface;
	
function Initialize: integer;
var
	iCounter, iFileIndex, iFoundIndex: integer;
begin

	tstrlistMasters := TStringList.Create;
	iFoundIndex := tstrlistMasters.IndexOf(strFileName);
	
	if iFoundIndex > -1 then
		tstrlistMasters.Delete(iFoundIndex);

	iFileIndex := IsFileAlreadyCreated(strFileName);
	
	if (bUseExistingFile = true) and (iFileIndex > -1) then
		fileDest := FileByIndex(iFileIndex)
	else
		fileDest := CreateUniqueFile();
		
	for iCounter := 0 to tstrlistMasters.Count - 1 do
		AddMasterIfMissing(fileDest, tstrlistMasters[iCounter]);
	
	//Factions
	bBoomers := true;
	bBoS := true;
	bEnclave := true;
	bLegion := true;
	bMarkedMen := true;
	bNCR := true;
	bOutcasts := true;
	bPowderGangers := true;
	
	bFiends := true;
	bSlavers := true;
	bTalon := true;
	
	//Mobs
	bNightkin := true;
	bSuperMutants := true;
	bCentaurs := true;
	
	bFeralGhouls := true;
	bLobotomites := true;
	
	bChinese := true;
	bTribals := true;
	bBandits := true;
	bRaiders := true;
	
	bAbominations := true;
	bAliens := true;

	bRobots := false;
	bAlienRobots := false;
	
	bDeathclaws := false;
	bTunnellers := false;
	bTrogs := false;
	bLakelurks := false;
	bSpores := false;
	bMirelurks := true;
	bAnimals := false;
	bInsects := false;

	tstrlistAlienRobots := TStringList.Create;
	tstrlistAlienRobots.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\001_Alien Robots.txt');
	
	tstrlistAbominations := TStringList.Create;
	tstrlistAbominations.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\002_Abominations.txt');
	
	tstrlistAliens := TStringList.Create;
	tstrlistAliens.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\003_Aliens.txt');
	
	tstrlistBandits := TStringList.Create;
	tstrlistBandits.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\004_Bandits.txt');
	
	tstrlistFiends := TStringList.Create;
	tstrlistFiends.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\005_Fiends.txt');
	
	tstrlistMarkedMen := TStringList.Create;
	tstrlistMarkedMen.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\008_Marked Men.txt');
	
	tstrlistSlavers := TStringList.Create;
	tstrlistSlavers.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\009_Slavers.txt');
	
	tstrlistPowderGangers := TStringList.Create;
	tstrlistPowderGangers.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\011_Powder Gangers.txt');
	
	tstrlistTalon := TStringList.Create;
	tstrlistTalon.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\013_Talon.txt');
	
	tstrlistRaiders := TStringList.Create;
	tstrlistRaiders.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\014_Raiders.txt');
	
	tstrlistCentaurs := TStringList.Create;
	tstrlistCentaurs.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\015_Centaurs.txt');
	
	tstrlistNightkin := TStringList.Create;
	tstrlistNightkin.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\016_Nightkin.txt');
	
	tstrlistSuperMutants := TStringList.Create;
	tstrlistSuperMutants.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\017_Super Mutants.txt');
	
	tstrlistBoomers := TStringList.Create;
	tstrlistBoomers.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\018_Boomers.txt');
	
	tstrlistOutcasts := TStringList.Create;
	tstrlistOutcasts.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\019_Outcasts.txt');
	
	tstrlistBoS := TStringList.Create;
	tstrlistBoS.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\020_BoS.txt');
	
	tstrlistNCR := TStringList.Create;
	tstrlistNCR.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\021_NCR.txt');
	
	tstrlistLegion := TStringList.Create;
	tstrlistLegion.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\022_Legion.txt');
	
	tstrlistEnclave := TStringList.Create;
	tstrlistEnclave.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\024_Enclave.txt');
	
	tstrlistTribals := TStringList.Create;
	tstrlistTribals.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\025_Tribals.txt');
	
	tstrlistChinese := TStringList.Create;
	tstrlistChinese.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\026_Chinese.txt');
	
	tstrlistFeralGhouls := TStringList.Create;
	tstrlistFeralGhouls.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\027_Feral Ghouls.txt');
	
	tstrlistLobotomites := TStringList.Create;
	tstrlistLobotomites.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\029_Lobotomites.txt');
	
	tstrlistDeathclaws := TStringList.Create;
	tstrlistDeathclaws.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\030_Deathclaws.txt');
	
	tstrlistTunnellers := TStringList.Create;
	tstrlistTunnellers.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\090_Tunnellers.txt');
	
	tstrlistTrogs := TStringList.Create;
	tstrlistTrogs.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\091_Trogs.txt');
	
	tstrlistLakelurks := TStringList.Create;
	tstrlistLakelurks.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\093_Lakelurks.txt');
	
	tstrlistSpores := TStringList.Create;
	tstrlistSpores.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\095_Spores.txt');
	
	tstrlistRobots := TStringList.Create;
	tstrlistRobots.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\096_Robots.txt');
	
	tstrlistMirelurks := TStringList.Create;
	tstrlistMirelurks.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\097_Mirelurks.txt');
	
	tstrlistAnimals := TStringList.Create;
	tstrlistAnimals.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\098_Animals.txt');
	
	tstrlistInsects := TStringList.Create;
	tstrlistInsects.LoadFromFile(ScriptsPath + 'FyTy\More Spawns\099_Insects.txt');
	
	tstrlistAll := TStringList.Create;
	tstrlistAll.Duplicates := dupIgnore;
	
	if bBoomers = true then
		tstrlistAll.AddStrings(tstrlistBoomers);

	if bBoS = true then
		tstrlistAll.AddStrings(tstrlistBoS);

	if bEnclave = true then
		tstrlistAll.AddStrings(tstrlistEnclave);

	if bLegion = true then
		tstrlistAll.AddStrings(tstrlistLegion);

	if bMarkedMen = true then
		tstrlistAll.AddStrings(tstrlistMarkedMen);

	if bNCR = true then
		tstrlistAll.AddStrings(tstrlistNCR);

	if bOutcasts = true then
		tstrlistAll.AddStrings(tstrlistOutcasts);

	if bPowderGangers = true then
		tstrlistAll.AddStrings(tstrlistPowderGangers);

	if bFiends = true then
		tstrlistAll.AddStrings(tstrlistFiends);

	if bSlavers = true then
		tstrlistAll.AddStrings(tstrlistSlavers);

	if bTalon = true then
		tstrlistAll.AddStrings(tstrlistTalon);

	if bNightkin = true then
		tstrlistAll.AddStrings(tstrlistNightkin);

	if bSuperMutants = true then
		tstrlistAll.AddStrings(tstrlistSuperMutants);

	if bCentaurs = true then
		tstrlistAll.AddStrings(tstrlistCentaurs);

	if bFeralGhouls = true then
		tstrlistAll.AddStrings(tstrlistFeralGhouls);

	if bLobotomites = true then
		tstrlistAll.AddStrings(tstrlistLobotomites);

	if bChinese = true then
		tstrlistAll.AddStrings(tstrlistChinese);

	if bTribals = true then
		tstrlistAll.AddStrings(tstrlistTribals);

	if bBandits = true then
		tstrlistAll.AddStrings(tstrlistBandits);

	if bRaiders = true then
		tstrlistAll.AddStrings(tstrlistRaiders);

	if bAbominations = true then
		tstrlistAll.AddStrings(tstrlistAbominations);

	if bAliens = true then
		tstrlistAll.AddStrings(tstrlistAliens);

	if bRobots = true then
		tstrlistAll.AddStrings(tstrlistRobots);

	if bAlienRobots = true then
		tstrlistAll.AddStrings(tstrlistAlienRobots);

	if bDeathclaws = true then
		tstrlistAll.AddStrings(tstrlistDeathclaws);
		
	if bTunnellers = true then
		tstrlistAll.AddStrings(tstrlistTunnellers);

	if bTrogs = true then
		tstrlistAll.AddStrings(tstrlistTrogs);

	if bLakelurks = true then
		tstrlistAll.AddStrings(tstrlistLakelurks);

	if bSpores = true then
		tstrlistAll.AddStrings(tstrlistSpores);

	if bMirelurks = true then
		tstrlistAll.AddStrings(tstrlistMirelurks);

	if bAnimals = true then
		tstrlistAll.AddStrings(tstrlistAnimals);

	if bInsects = true then
		tstrlistAll.AddStrings(tstrlistInsects);
	
end;

function IsFileAlreadyCreated(strToCheck: string): integer;
var
	iCounter: integer;
	fileCurrent: IInterface;
	strMaster: string;
begin

	for iCounter := 0 to FileCount - 1 do begin
	
			fileCurrent := FileByIndex(iCounter);
			
			if pos('.exe', strMaster) = 0 then
				tstrlistMasters.Append(GetFileName(fileCurrent));
			
			if GetFileName(fileCurrent) = strToCheck then begin
			
					Result := iCounter;
					
					exit;
					
			end;
	
	end;
	
	Result := -1;

end;

function CreateUniqueFile(): IInterface;
var
	iCounter: integer;
	strFileNameCurrent, strSuffix: string;
begin
	
	iCounter := 0;
	
	if bCopyIfESP = false then
		strSuffix := '.esm'
	else
		strSuffix := '.esp';
	
	repeat
	
			inc(iCounter);
			strFileNameCurrent := format(strFileNamePrefix + '%.3d', [iCounter]) + strSuffix;
	
	until IsFileAlreadyCreated(strFileNameCurrent) = -1;
	
	Result := AddNewFileName(strFileNameCurrent);

end;

Procedure SpawnNPC(e: IInterface; strSpawn: string);
begin
	
	//AddMasterIfMissing(FileDest, GetFileName(GetFile(e)));
	
	if tstrlistAll.IndexOf(strSpawn) > -1 then
		wbCopyElementToFile(e, fileDest, true, true);
			
end;

function Process(e: IInterface): integer;
var
	eNPCToCheck: IInterface;
	iCounter, iRand: integer;
	strNAMEfromNPC: string;
begin
	
	if Signature(e) <> 'ACHR' then
		if Signature(e) <> 'ACRE' then
			exit;
	
	Randomize;
	if iMinMultiplier < 1 then
		iRand := Random(iMaxMultiplier + 1)
	else
		iRand := RandomRange(iMinMultiplier, iMaxMultiplier);
	
	eNPCToCheck := MasterOrSelf(e);
	//AddMasterIfMissing(fileDest, GetFileName(GetFile(e)));
	
	if OverrideCount(eNPCToCheck) > 0 then
		eNPCToCheck := WinningOverride(eNPCToCheck);
		
	if (bCopyIfESP = false) and (pos('.esp', GetFileName(GetFile(eNPCToCheck))) > 0) then
		exit;
	
	//AddMessage('Processing: ' + FullPath(e)); //Uncomment to find which specific NPC is causing an issue. Will cause low performance!
	
	strNAMEfromNPC := GetEditValue(ElementByPath(eNPCToCheck, 'NAME - Base'));
	
	if iRand > 0 then repeat
	
		SpawnNPC(eNPCToCheck, strNAMEfromNPC);
	
		iCounter := iCounter + 1;
	
	until iCounter = iRand;
	
end;


function Finalize: integer;
begin

	if bCopyIfESP = false then
		SetIsESM(fileDest, true);

	CleanMasters(fileDest);
	SortMasters(fileDest);

  tstrlistAll.Free;
	tstrlistAlienRobots.Free;
	tstrlistAbominations.Free;
	tstrlistAliens.Free;
	tstrlistBandits.Free;
	tstrlistFiends.Free;
	tstrlistMarkedMen.Free;
	tstrlistSlavers.Free;
	tstrlistPowderGangers.Free;
	tstrlistTalon.Free;
	tstrlistRaiders.Free;
	tstrlistCentaurs.Free;
	tstrlistNightkin.Free;
	tstrlistSuperMutants.Free;
	tstrlistBoomers.Free;
	tstrlistOutcasts.Free;
	tstrlistBoS.Free;
	tstrlistNCR.Free;
	tstrlistLegion.Free;
	tstrlistEnclave.Free;
	tstrlistTribals.Free;
	tstrlistChinese.Free;
	tstrlistFeralGhouls.Free;
	tstrlistLobotomites.Free;
	tstrlistDeathclaws.Free;
	tstrlistTunnellers.Free;
	tstrlistTrogs.Free;
	tstrlistLakelurks.Free;
	tstrlistSpores.Free;
	tstrlistRobots.Free;
	tstrlistMirelurks.Free;
	tstrlistAnimals.Free;
	tstrlistInsects.Free;
	
end;

end.
