unit userscript;

const
	bUseExistingFile = false; //Whether or not to use an existing .esp generated by this script
	strFileNamePrefix = 'FyTy - NPCs Use Ammo'; //Used when generating a unique .esp file
	strFileName = 'FyTy - NPCs Use Ammo.esm'; //The name of an existing mod file. Only used if: bUseExistingFile = true;
	bCopyIfESP = true;
	
var
	fileDest: IInterface;
	tstrlistMasters, tstrlistProcessedWeapons, tstrlistAmmoKeywordsIgnore,
	tstrlistNumbers, tstrlistLevelledListFormIDsToSave: TStringList;
	groupLVLI: IwbGroupRecord;
	
function IsFileAlreadyCreated(strToCheck: string): integer;
var
	iCounter: integer;
	fileCurrent: IInterface;
	strMaster: string;
begin

	for iCounter := 0 to FileCount - 1 do begin
	
			fileCurrent := FileByIndex(iCounter);
			
			if pos('.exe', strMaster) = 0 then
				tstrlistMasters.Append(GetFileName(fileCurrent));
			
			if GetFileName(fileCurrent) = strToCheck then begin
			
					Result := iCounter;
					
					exit;
					
			end;
	
	end;
	
	Result := -1;

end;

function CreateUniqueFile(): IInterface;
var
	iCounter: integer;
	strFileNameCurrent, strSuffix: string;
begin
	
	iCounter := 0;
	
	if bCopyIfESP = false then
		strSuffix := '.esm'
	else
		strSuffix := '.esp';
	
	repeat
	
			inc(iCounter);
			strFileNameCurrent := format(strFileNamePrefix + '%.3d', [iCounter]) + strSuffix;
	
	until IsFileAlreadyCreated(strFileNameCurrent) = -1;
	
	//AddMessage(strFileNameCurrent);
	
	Result := AddNewFileName(strFileNameCurrent);

end;

procedure FillAmmoKeywordsToIgnore();
begin

	tstrlistAmmoKeywordsIgnore.Add('Match');
	tstrlistAmmoKeywordsIgnore.Add('RockIt');
	tstrlistAmmoKeywordsIgnore.Add('GRA');
	tstrlistAmmoKeywordsIgnore.Add('NVDLC05');
	tstrlistAmmoKeywordsIgnore.Add('Special');
	tstrlistAmmoKeywordsIgnore.Add('+P');
	//FatMan
	tstrlistAmmoKeywordsIgnore.Add('LowYield');
	tstrlistAmmoKeywordsIgnore.Add('Timed');
	tstrlistAmmoKeywordsIgnore.Add('BigKid');
	tstrlistAmmoKeywordsIgnore.Add('TinyTots');
	//Guns
	tstrlistAmmoKeywordsIgnore.Add('HollowPoint');
	tstrlistAmmoKeywordsIgnore.Add('JHP');
	tstrlistAmmoKeywordsIgnore.Add('HandLoad');
	tstrlistAmmoKeywordsIgnore.Add('JunkRounds');
	tstrlistAmmoKeywordsIgnore.Add('ArmorPiercing');
	tstrlistAmmoKeywordsIgnore.Add('Bulk');
	tstrlistAmmoKeywordsIgnore.Add('Surplus');
	//Flamer
	tstrlistAmmoKeywordsIgnore.Add('Homemade');
	tstrlistAmmoKeywordsIgnore.Add('Optimized');
	//Auto Laser
	tstrlistAmmoKeywordsIgnore.Add('MaxCharge');
	tstrlistAmmoKeywordsIgnore.Add('OverCharge');
	//Missile
	tstrlistAmmoKeywordsIgnore.Add('HighVelocity');
	tstrlistAmmoKeywordsIgnore.Add('HighExplosive');
	tstrlistAmmoKeywordsIgnore.Add('Hive');
	//Shotgun
	tstrlistAmmoKeywordsIgnore.Add('GaSlug');
	tstrlistAmmoKeywordsIgnore.Add('GaMagnum');
	tstrlistAmmoKeywordsIgnore.Add('BeanBag');
	tstrlistAmmoKeywordsIgnore.Add('CoinShot');
	tstrlistAmmoKeywordsIgnore.Add('DragonsBreath');
	tstrlistAmmoKeywordsIgnore.Add('Flechette');
	tstrlistAmmoKeywordsIgnore.Add('PulseSlug');
	tstrlistAmmoKeywordsIgnore.Add('40Buck');
	tstrlistAmmoKeywordsIgnore.Add('30Buck');
	tstrlistAmmoKeywordsIgnore.Add('BuckMagnum');
	//Rifle
	tstrlistAmmoKeywordsIgnore.Add('Plinking');
	//Grenade Launcher
	tstrlistAmmoKeywordsIgnore.Add('GrenadePlasma');
	tstrlistAmmoKeywordsIgnore.Add('GrenadePulse');
	tstrlistAmmoKeywordsIgnore.Add('Incendiary');

end;

function IsRegularAmmo(strEDID, strFULL: string): Boolean;
var
	iCounter: integer;
begin

	Result := True;
	
	for iCounter := 0 to tstrlistAmmoKeywordsIgnore.Count - 1 do begin
	
		if (pos(tstrlistAmmoKeywordsIgnore[iCounter], strEDID) > 0) or (pos(tstrlistAmmoKeywordsIgnore[iCounter], strFULL) > 0) then begin
			
			//AddMessage(strAMMO + ',' + tstrlistAmmoKeywordsIgnore[iCounter]);
			Result := False;
			exit;
		
		end;
	
	end;

end;

function RemoveSubstring(strSource, strToRemove: string): string;
var
	strResult: string;
begin

	strResult := strSource;
	
	while Pos(strToRemove, strResult) > 0 do
		Delete(strResult, Pos(strToRemove, strResult), length(strToRemove));
	
	Result := strResult;

end;

function RemoveAllNotNumbers(strSource: string): string;
var
	strText, strChar: string;
	iCounter: integer;
begin

	//AddMessage('RemoveAllNotNumbers! - ' + strSource);
	
	strText := strSource;
	
	while Length(strText) > 0 do begin
	
		strChar := LeftStr(strText, 1);
		
		if tstrlistNumbers.IndexOf(strChar) > -1 then
			Result := Result + strChar;
		
		Delete(strText, 1, 1);
	
	end;
	
end;

function RemoveSymbols(strSource: string): string;
var
	strResult: string;
begin

	strResult := strSource;
	//AddMessage('RemoveSymbols() Begin - ' + strResult);
	
	strResult := RemoveSubstring(strResult, ' ');
	strResult := RemoveSubstring(strResult, '/');
	strResult := RemoveSubstring(strResult, '\');
	strResult := RemoveSubstring(strResult, '.');
	strResult := RemoveSubstring(strResult, ',');
	strResult := RemoveSubstring(strResult, ')');
	strResult := RemoveSubstring(strResult, '(');
	strResult := RemoveSubstring(strResult, '.');
	strResult := RemoveSubstring(strResult, '+');
	strResult := RemoveSubstring(strResult, '-');
	strResult := RemoveSubstring(strResult, '?');
	strResult := RemoveSubstring(strResult, '*');
	strResult := RemoveSubstring(strResult, '&');
	strResult := RemoveSubstring(strResult, '^');
	strResult := RemoveSubstring(strResult, '%');
	strResult := RemoveSubstring(strResult, '$');
	strResult := RemoveSubstring(strResult, '#');
	strResult := RemoveSubstring(strResult, '@');
	strResult := RemoveSubstring(strResult, '!');
	strResult := RemoveSubstring(strResult, '`');
	strResult := RemoveSubstring(strResult, '~');
	strResult := RemoveSubstring(strResult, '<');
	strResult := RemoveSubstring(strResult, '>');
	strResult := RemoveSubstring(strResult, '|');
	strResult := RemoveSubstring(strResult, '=');
	strResult := RemoveSubstring(strResult, '_');
	
	//AddMessage('RemoveSymbols() END - ' + strResult);
	Result := strResult;

end;

function Initialize: integer;
var
	iFoundIndex, iFileIndex, iCounter: integer;
begin

	tstrlistProcessedWeapons := TStringList.Create;
	
	tstrlistAmmoKeywordsIgnore := TStringList.Create;
	
	tstrlistMasters := TStringList.Create;
	
	tstrlistLevelledListFormIDsToSave := TStringList.Create;
	
	iFoundIndex := tstrlistMasters.IndexOf(strFileName);
	
	if iFoundIndex > -1 then
		tstrlistMasters.Delete(iFoundIndex);

	iFileIndex := IsFileAlreadyCreated(strFileName);
	
	if (bUseExistingFile = true) and (iFileIndex > -1) then
		fileDest := FileByIndex(iFileIndex)
	else
		fileDest := CreateUniqueFile();
		
	for iCounter := 0 to tstrlistMasters.Count - 1 do
		AddMasterIfMissing(fileDest, tstrlistMasters[iCounter]);
		
	groupLVLI := CreateGroupIfNotPresent('LVLI');
	
	FillAmmoKeywordsToIgnore();
	
	tstrlistNumbers := TStringList.Create;
	tstrlistNumbers.Add('0');
	tstrlistNumbers.Add('1');
	tstrlistNumbers.Add('2');
	tstrlistNumbers.Add('3');
	tstrlistNumbers.Add('4');
	tstrlistNumbers.Add('5');
	tstrlistNumbers.Add('6');
	tstrlistNumbers.Add('7');
	tstrlistNumbers.Add('8');
	tstrlistNumbers.Add('9');
  
end;

function CreateGroupIfNotPresent(strGroup: string): IwbGroupRecord;
var
	group: IwbGroupRecord;
begin

	group := GroupBySignature(fileDest, strGroup);
	
	if not Assigned(group) then
		group := Add(fileDest, strGroup, False);
		
	Result := group;

end;

function CreateLevelledListAmmo(eWEAP, eAmmoList: IInterface; strSuffix: string; iClipSize: integer; fStartClipMult, fInc: single): IInterface;
var
	iAmmoCounter, iCounter, iNumBullets: integer;
	eAMMO, eLVLI, eEDID, eAmmoTypeEntries, eEntries, eEntryCurrent,
	eWeaponLVLI, eMainLVLI: IInterface;
	fNewClipMult, fCondition: single;
	strEDID: string;
begin

	fNewClipMult := fStartClipMult;
	
	eAmmoTypeEntries := ElementByPath(eAmmoList, 'FormIDs');
	
	//Create levelled list for current ammo, each entry having previous + 1/2 weapon's clip capacity
	for iAmmoCounter := 0 to ElementCount(eAmmoTypeEntries) - 1 do begin
		
		eAMMO := LinksTo(ElementByIndex(eAmmoTypeEntries, iAmmoCounter));
		
		eLVLI := Add(groupLVLI, 'LVLI', True);
		eEDID := Add(eLVLI, 'EDID', False);
		eEntries := Add(eLVLI, 'Leveled List Entries', False);
		
		eEntryCurrent := ElementByIndex(eEntries, 0);
		
		fNewClipMult := fStartClipMult;
		SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', IntToStr(round(iClipSize * fNewClipMult)));
		
		strEDID := 'AAAFyTy' + RemoveSubstring(GetElementEditValues(eWEAP, 'EDID'), 'Weap') + RemoveSymbols(GetElementEditValues(eAMMO, 'FULL')) + strSuffix;
		
		SetElementEditValues(eLVLI, 'EDID', strEDID);
		SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eAMMO, 'Record Header\FormID'));
		SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
	
		for iCounter := 1 to 3 do begin
	
			eEntryCurrent := ElementAssign(eEntries, HighInteger, nil, false);
			
			fNewClipMult := fNewClipMult + fInc;
			iNumBullets := round(iClipSize * fNewClipMult);
			
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', iNumBullets);
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eAMMO, 'Record Header\FormID'));
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
	
		end;
		
		//If current ammo is not AP/JHP/Junk/etc
		if IsRegularAmmo(GetElementEditValues(eAMMO, 'EDID'), GetElementEditValues(eAMMO, 'FULL')) then begin
	
			//AddMessage('Regular ammo! - ' + GetElementEditValues(eAMMO, 'EDID'));
			
			eWeaponLVLI := Add(groupLVLI, 'LVLI', True);
			
			eEDID := Add(eWeaponLVLI, 'EDID', False);
			strEDID := 'AAAFyTy' + RemoveSubstring(GetElementEditValues(eWEAP, 'EDID'), 'Weap') + 'Cond' + RemoveSymbols(GetElementEditValues(eAMMO, 'FULL')) + strSuffix;
			//AddMessage(strEDID);
			SetElementEditValues(eWeaponLVLI, 'EDID', strEDID);
			
			eEntries := Add(eWeaponLVLI, 'Leveled List Entries', False);
			
			if strSuffix = 'Low' then
				fCondition := 0.25
			else if strSuffix = 'Med' then
				fCondition := 0.40
			else if strSuffix = 'High' then
				fCondition := 0.55;
			
			//Add Weapons with condition
			eEntryCurrent := ElementByIndex(eEntries, 0);
			Add(eEntryCurrent, 'COED', False);
			
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eWEAP, 'Record Header\FormID'));
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', '1');
			SetElementEditValues(eEntryCurrent, 'COED - Extra Data\Item Condition', FloatToStr(fCondition));
			
			for iCounter := 1 to 3 do begin
			
				fCondition := fCondition + 0.05;
				
				eEntryCurrent := ElementAssign(eEntries, HighInteger, nil, false);
				Add(eEntryCurrent, 'COED', False);
				
				SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
				SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', '1');
				SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eWEAP, 'Record Header\FormID'));
				SetElementEditValues(eEntryCurrent, 'COED - Extra Data\Item Condition', FloatToStr(fCondition));
			
			end;
			
			//Create main levelled list
			
			eMainLVLI := Add(groupLVLI, 'LVLI', True);
			eEDID := Add(eMainLVLI, 'EDID', False);
			eEntries := Add(eMainLVLI, 'Leveled List Entries', False);
			
			strEDID := 'AAAFyTyWithAmmo' + RemoveSubstring(GetElementEditValues(eWEAP, 'EDID'), 'Weap') + RemoveSymbols(GetElementEditValues(eAMMO, 'QNAM')) + strSuffix;
			SetElementEditValues(eMainLVLI, 'EDID', strEDID);
			
			SetElementEditValues(eMainLVLI, 'LVLF - Flags\Use All', '1');
			
			//Add the root levelled list (weapon cond lli + ammo lli) to the text file
			tstrlistLevelledListFormIDsToSave.Add(IntToHex(GetLoadOrderFormID(eMainLVLI), 8) + ',' + GetElementEditValues(eMainLVLI, 'Record Header\FormID'));
			
			
			//Add weapon list
			eEntryCurrent := ElementByIndex(eEntries, 0);
			
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', '1');
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eWeaponLVLI, 'Record Header\FormID'));
			
			
			//Add ammo list
			eEntryCurrent := ElementAssign(eEntries, HighInteger, nil, false);
			
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Level', '1');
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Count', '1');
			//AddMessage(GetElementEditValues(eLVLI, 'Record Header\FormID'));
			SetElementEditValues(eEntryCurrent, 'LVLO - Base Data\Reference', GetElementEditValues(eLVLI, 'Record Header\FormID'));
			
		end;	
	
	end;
	
end;

function GetLastOverride(e: IInterface): IInterface;
var
	eRec: IInterface;
begin

	eRec := MasterOrSelf(e);
	//AddMessage('eRec is: ' + Signature(eRec));
	
	if OverrideCount(eRec) > 0 then
		eRec := WinningOverride(eRec);
		
	Result := eRec;

end;

function Process(e: IInterface): integer;
var
	eWEAP, eAmmoList, eAmmoCurrent, eEntryCurrent: IInterface;
	iCreateCounter, iCounter, iClipSize: Integer;
begin

	eWEAP := GetLastOverride(e);

	if (Signature(eWEAP) <> 'WEAP')then
		exit;
	
	if (ElementExists(eWEAP, 'NAM0') = false) then
		exit;
		
	if tstrlistProcessedWeapons.IndexOf(GetElementEditValues(eWEAP, 'EDID')) > -1 then
		exit;
	
	if GetElementEditValues(eWEAP, 'DNAM - DNAM\Flags 1\Non-Playable') = '1' then
		exit;
		
	if Pos('RockIt', GetElementEditValues(eWEAP, 'EDID')) > 0 then
		exit;
	
  //AddMessage('Processing: ' + FullPath(eWEAP));
	//AddMessage(GetElementEditValues(eWEAP, 'DNAM - DNAM\Flags 2\NPCs Use Ammo'));
	
	if GetElementEditValues(eWEAP, 'DNAM - DNAM\Flags 2\NPCs Use Ammo') = '0' then begin
	
		CreateGroupIfNotPresent('WEAP');
		eWEAP := wbCopyElementToFile(eWEAP, fileDest, false, true);
		SetElementEditValues(eWEAP, 'DNAM - DNAM\Flags 2\NPCs Use Ammo', '1');
		
	end;
	
	iClipSize := StrToInt(GetElementEditValues(eWEAP, 'DATA - DATA\Clip Size'));
	eAmmoList := LinksTo(ElementByPath(eWEAP, 'NAM0'));
	
	//Low count
	CreateLevelledListAmmo(eWEAP, eAmmoList, 'Low', iClipSize, 1.0, 0.5);
	
	//Med count
	CreateLevelledListAmmo(eWEAP, eAmmoList, 'Med', iClipSize, 2.0, 0.5);
	
	//High count
	CreateLevelledListAmmo(eWEAP, eAmmoList, 'High', iClipSize, 3.0, 0.5);
	
	tstrlistProcessedWeapons.Add(GetElementEditValues(eWEAP, 'EDID'));

end;


function Finalize: integer;
begin
	
	tstrlistProcessedWeapons.Free;
	tstrlistMasters.Free;
	tstrlistAmmoKeywordsIgnore.Free;
	
	tstrlistLevelledListFormIDsToSave.SaveToFile(ScriptsPath + 'FyTy\NPCsUseAmmo\01CreatedLLIs.txt');
	tstrlistLevelledListFormIDsToSave.Free;
end;

end.